FROM rancher/k3s:latest
#RUN apk --update --no-cache add\
 #curl\
 #openrc
#RUN apt update -y
#RUN apt install systemd-sysv -y
#| INSTALL_K3S_CHANNEL=latest K3S_TOKEN='mysecrettoken2' sh -s - server --server https://192.168.1.150:6443" > test.sh
CMD ["/bin/sh", "test.sh"]
#| INSTALL_K3S_CHANNEL=latest K3S_TOKEN='mysecrettoken2' sh -s - server --server https://192.168.1.150:6443"]