version: '3'
services:
   agent:
    image: "rancher/k3s:latest"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://192.168.1.150:6443
    - K3S_TOKEN=K10514f65b26a764192c121571443240cfc8c4c06a6f69e5f595b736ff4b7ca50b1::server:mysecrettoken2

volumes:
  k3s-server: {}
