version: '3'
services:
  initialnode:
    image: rancher/k3s:latest

    command: server --no-deploy traefik --cluster-init
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=mope
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
    - 6443:6443
  server-joiner:
    image: rancher/k3s:latest
    command: server --server https://initialnode:6443
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
   
    - K3S_TOKEN=mope
    ports:
    - 6444-6450:6443
  agent:
    image: rancher/k3s:latest
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://initialnode:6443
    - K3S_TOKEN=mope
volumes:
  k3s-server: {}