version: '3'
services:
    javasocketserver:
        build: ./servidor
        ports:
            - "8080:4444"
    nodejswebserver:
        build: ./nodejs
        ports:
            - "8081:3000"
    nginx:
        image: nginx:latest
        ports:
            - "8082:80"
          