FROM nginx:latest
#COPY default.conf /etc/nginx/conf.d/default.conf
#RUN mkdir /usr/share/nginx/html/davidservice/
#COPY david.html /usr/share/nginx/html/davidservice/david.html
COPY david.html /usr/share/nginx/html/index.html